FROM busybox:glibc
LABEL org.opencontainers.image.source='https://gitcode.com/boostkit/cloud-native'
LABEL version='devel'
LABEL release='1'
LABEL name='kae-device-plugin'
LABEL summary='Kunpeng KAE device plugin for Kubernetes'
COPY ./bin/kae-device-plugin /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/kae-device-plugin"]
