# Build k8s-mpam-controller
FROM golang:1.25.0 as builder

WORKDIR /go/src/k8s-mpam-controller
COPY . /go/src/k8s-mpam-controller

# use "go get" instead of "go mod" to bypass client-go dependence issue
# use build.sh to bypass error: "The command '/bin/sh -c go get -d -v ./...' returned a non-zero code: 1"
RUN make mpam-build-local

# Create k8s-mpam-controller image
FROM busybox:glibc

COPY --from=builder /go/src/k8s-mpam-controller/bin/k8s-mpam-controller /usr/bin/agent
