# Runtime image for kunpeng-tap-pcore-biding.
#
# Build the binary first, then build this image:
#   make kunpeng-tap-build-pcore-biding
#   docker build -f Dockerfile.kunpeng-tap-pcore-biding -t kunpeng-tap-pcore-biding:latest .
FROM busybox:glibc

COPY bin/kunpeng-tap-pcore-biding /usr/local/bin/kunpeng-tap-pcore-biding

ENTRYPOINT ["/usr/local/bin/kunpeng-tap-pcore-biding"]

LABEL maintainer="Kunpeng Boostkit Team"
LABEL description="NRI plugin for binding kata pod cpuset to physical-core sibling CPUs"
