# Runtime image for kunpeng-tap-pcore-biding.
#
# Build the hardened ARM64 binary and image:
#   make kunpeng-tap-pcore-biding-docker-build
FROM busybox:glibc

COPY bin/kunpeng-tap-pcore-biding /usr/local/bin/kunpeng-tap-pcore-biding

ENTRYPOINT ["/usr/local/bin/kunpeng-tap-pcore-biding"]

LABEL maintainer="Kunpeng Boostkit Team"
LABEL description="NRI plugin for binding kata pod cpuset to physical-core sibling CPUs"
