# Copyright 2017 The Prometheus Authors
# Copyright (c) 2025 Huawei Technology corp.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.25 AS builder
WORKDIR /go/src/kunpeng.huawei.com/kunpeng-cloud-computing/
COPY . .

# set proxy if needed.
# replace the $http_proxy and $https_proxy below with your own proxy if needed. 
# ENV http_proxy $http_proxy
# ENV https_proxy $https_proxy

# set go env
RUN go env -w GO111MODULE=on && \
    go env -w GOPROXY=https://mirrors.huaweicloud.com/repository/goproxy/,https://goproxy.cn,https://mirrors.aliyun.com/goproxy/ && \
    go env -w GONOSUMDB=*

# download dependencies manually, instead of using libkperf.sh
RUN sed -i 's|get_dependencies=true|get_dependencies=false|g' libkperf.sh
RUN apt remove -y g++ && apt autoremove -y
RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends -y make cmake python3 libnuma-dev libc6 gcc g++-12 \
    && cp /usr/bin/g++-12 /usr/bin/g++ \
    && apt-get clean && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# build kunpeng-perf-monitor
RUN make -f Makefile.kunpeng-perf-monitor build


FROM quay.io/prometheus/busybox-linux-arm64:latest
# copy binary and libraries from builder
COPY --from=builder /go/src/kunpeng.huawei.com/kunpeng-cloud-computing/bin/kunpeng-perf-monitor /bin/kunpeng-perf-monitor
COPY --from=builder /go/src/kunpeng.huawei.com/kunpeng-cloud-computing/pkg/kunpeng-perf-monitor/libkperf/lib/* /lib/

RUN mkdir -p /lib/aarch64-linux-gnu
COPY --from=builder /lib/aarch64-linux-gnu/libc.so.6 /lib/aarch64-linux-gnu/
COPY --from=builder /lib/aarch64-linux-gnu/libstdc++.so.6 /lib/aarch64-linux-gnu/
COPY --from=builder /lib/aarch64-linux-gnu/libgcc_s.so.1 /lib/aarch64-linux-gnu/
COPY --from=builder /lib/aarch64-linux-gnu/libm.so.6 /lib/aarch64-linux-gnu/
COPY --from=builder /lib/ld-linux-aarch64.so.1 /lib/

# set LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH

EXPOSE      9100
ENTRYPOINT  [ "/bin/kunpeng-perf-monitor" ]