apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kae-admission-webhook
    app.kubernetes.io/managed-by: kustomize
  name: kae-admission-webhook
  namespace: kae-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: kunpeng-kae-plugin
