apiVersion: v1
kind: ServiceAccount
metadata:
  name: kae-device-plugin
  namespace: kae-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kae-device-plugin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kae-device-plugin
subjects:
- kind: ServiceAccount
  name: kae-device-plugin
  namespace: kae-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kae-device-plugin
