// Code generated by MockGen. DO NOT EDIT.
// Source: qemu.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_qemu.go -source qemu.go
//

// Package mock_qemu is a generated GoMock package.
package mock_qemu

import (
	reflect "reflect"

	v1 "github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockQemuKvmInterface is a mock of QemuKvmInterface interface.
type MockQemuKvmInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQemuKvmInterfaceMockRecorder
	isgomock struct{}
}

// MockQemuKvmInterfaceMockRecorder is the mock recorder for MockQemuKvmInterface.
type MockQemuKvmInterfaceMockRecorder struct {
	mock *MockQemuKvmInterface
}

// NewMockQemuKvmInterface creates a new mock instance.
func NewMockQemuKvmInterface(ctrl *gomock.Controller) *MockQemuKvmInterface {
	mock := &MockQemuKvmInterface{ctrl: ctrl}
	mock.recorder = &MockQemuKvmInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQemuKvmInterface) EXPECT() *MockQemuKvmInterfaceMockRecorder {
	return m.recorder
}

// CreateQemuKvmDevicesInfo mocks base method.
func (m *MockQemuKvmInterface) CreateQemuKvmDevicesInfo() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQemuKvmDevicesInfo")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQemuKvmDevicesInfo indicates an expected call of CreateQemuKvmDevicesInfo.
func (mr *MockQemuKvmInterfaceMockRecorder) CreateQemuKvmDevicesInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQemuKvmDevicesInfo", reflect.TypeOf((*MockQemuKvmInterface)(nil).CreateQemuKvmDevicesInfo))
}

// CreateQemuKvmDevicesInfoFromNodeStatus mocks base method.
func (m *MockQemuKvmInterface) CreateQemuKvmDevicesInfoFromNodeStatus(arg0 *v1.SriovNetworkNodeState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateQemuKvmDevicesInfoFromNodeStatus", arg0)
}

// CreateQemuKvmDevicesInfoFromNodeStatus indicates an expected call of CreateQemuKvmDevicesInfoFromNodeStatus.
func (mr *MockQemuKvmInterfaceMockRecorder) CreateQemuKvmDevicesInfoFromNodeStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQemuKvmDevicesInfoFromNodeStatus", reflect.TypeOf((*MockQemuKvmInterface)(nil).CreateQemuKvmDevicesInfoFromNodeStatus), arg0)
}

// DiscoverSriovDevicesVirtualInQemuKvm mocks base method.
func (m *MockQemuKvmInterface) DiscoverSriovDevicesVirtualInQemuKvm() ([]v1.InterfaceExt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverSriovDevicesVirtualInQemuKvm")
	ret0, _ := ret[0].([]v1.InterfaceExt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverSriovDevicesVirtualInQemuKvm indicates an expected call of DiscoverSriovDevicesVirtualInQemuKvm.
func (mr *MockQemuKvmInterfaceMockRecorder) DiscoverSriovDevicesVirtualInQemuKvm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverSriovDevicesVirtualInQemuKvm", reflect.TypeOf((*MockQemuKvmInterface)(nil).DiscoverSriovDevicesVirtualInQemuKvm))
}
