apiVersion: v1
kind: Pod
metadata:
  name: test-vf3
  namespace: sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: host-network-1822
spec:
  nodeName: compute01
  containers:
  - name: netperf 
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        openshift.io/huawei1822: '1'
      limits:
        openshift.io/huawei1822: '1'