FROM golang:1.23 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/sriov-network-operator
COPY . .

# 按续设置代理以保证容器内编译可正常拉取依赖
# ENV https_proxy=http://ip:port
# ENV http_proxy=http://ip:port
# 编译会涉及go依赖拉取，按需设置对应代理

RUN make _build-sriov-network-config-daemon BIN_PATH=build/_output/cmd

FROM quay.io/centos/centos:stream9
ARG MSTFLINT=mstflint

# 按需设置代理以保证容器内编译可正常拉取依赖
# ENV https_proxy=http://ip:port
# ENV http_proxy=http://ip:port

# We have to ensure that pciutils is installed. This package is needed for mstfwreset to succeed.
# xref pkg/vendors/mellanox/mellanox.go#L150
RUN ARCH_DEP_PKGS=$(if [ "$(uname -m)" != "s390x" ]; then echo -n ${MSTFLINT} ; fi) && yum -y install hwdata pciutils $ARCH_DEP_PKGS && yum clean all

# add utilk-linux and ethtool which are required by arm
RUN dnf install -y util-linux ethtool && dnf clean all

# 去除代理配置
# ENV https_proxy=
# ENV http_proxy=

LABEL io.k8s.display-name="sriov-network-config-daemon" \
      io.k8s.description="This is a daemon that manage and config sriov network devices in Kubernetes cluster"
COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/build/_output/cmd/sriov-network-config-daemon /usr/bin/
COPY bindata /bindata
CMD ["/usr/bin/sriov-network-config-daemon"]
