apiVersion: v1
kind: Pod
metadata:
  name: kata-clh-cpuset-limit-1
  namespace: default
  labels:
    app: kata-clh-cpuset-limit-test
spec:
  runtimeClassName: kata-clh
  restartPolicy: Never
  containers:
  - name: pause
    image: registry.aliyuncs.com/google_containers/pause:3.10.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: 32Mi
      limits:
        cpu: "1"
        memory: 32Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-clh-cpuset-limit-2
  namespace: default
  labels:
    app: kata-clh-cpuset-limit-test
spec:
  runtimeClassName: kata-clh
  restartPolicy: Never
  containers:
  - name: pause
    image: registry.aliyuncs.com/google_containers/pause:3.10.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: 32Mi
      limits:
        cpu: "2"
        memory: 32Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-clh-cpuset-limit-4
  namespace: default
  labels:
    app: kata-clh-cpuset-limit-test
spec:
  runtimeClassName: kata-clh
  restartPolicy: Never
  containers:
  - name: pause
    image: registry.aliyuncs.com/google_containers/pause:3.10.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2"
        memory: 32Mi
      limits:
        cpu: "4"
        memory: 32Mi
