apiVersion: v1
kind: Pod
metadata:
  name: kata-clh-cpuset-test-0
  namespace: default
  labels:
    app: kata-clh-cpuset-test
spec:
  runtimeClassName: kata-clh
  restartPolicy: Never
  containers:
  - name: pause
    image: registry.aliyuncs.com/google_containers/pause:3.10.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2"
        memory: 32Mi
      limits:
        cpu: "2"
        memory: 32Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-clh-cpuset-test-1
  namespace: default
  labels:
    app: kata-clh-cpuset-test
spec:
  runtimeClassName: kata-clh
  restartPolicy: Never
  containers:
  - name: pause
    image: registry.aliyuncs.com/google_containers/pause:3.10.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2"
        memory: 32Mi
      limits:
        cpu: "2"
        memory: 32Mi
